import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const siteKey = process.env.NEXT_PUBLIC_SITE_KEY;

   // Debug: Log the site key (it will be visible in page source but that's okay for debugging)
   console.log('🔑 Site Key:', siteKey ? 'LOADED' : 'MISSING');
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         {/* Show error if key is missing */}
         {!siteKey && (
          <div style={{ background: 'red', color: 'white', padding: '10px' }}>
            ⚠️ NEXT_PUBLIC_SITE_KEY is not set!
          </div>
        )}

        {siteKey && (
          <Script
            src={`https://www.google.com/recaptcha/api.js?render=${siteKey}`}
            strategy="afterInteractive"
            onLoad={() => console.log('✅ reCAPTCHA loaded')}
            onError={() => console.error('❌ reCAPTCHA failed to load')}
          />
        )}
        {children}
      </body>
    </html>
  );
}
